on:
  schedule:
  - cron: 0 6 * * 1
  workflow_dispatch:
name: Update Dependencies
jobs:
  package-update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: 12.x
        registry-url: https://npm.pkg.github.com
        scope: '@loopstudio'
    - name: set remote url
      run: git remote set-url --push origin https://$GITHUB_ACTOR:${{ secrets.DEPENDACOP_LOOPITO_PAT }}@github.com/$GITHUB_REPOSITORY
    - name: Dependacop
      uses: elestu/actions-dependacop@v1.0.4
      env:
        AUTHOR_EMAIL: hello@loopstudio.dev
        AUTHOR_NAME: Loopito
        EXECUTE: true
        GITHUB_TOKEN: ${{ secrets.DEPENDACOP_LOOPITO_PAT }}
        COMMIT_MESSAGE: 🛠 Update Dependencies
        NODE_AUTH_TOKEN: ${{ secrets.NPM_GITHUB_TOKEN }}
        LOG_LEVEL: debug
      with:
        args: -u --packageFile package.json --dep prod
